name: solid_software_test_task
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  auto_route: ^5.0.4
  bloc: ^8.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  auto_route_generator: any
  build_runner: ^2.2.1
  solid_lints: ^0.0.18

flutter:
  uses-material-design: true
  generate: true

